// Code generated by lesiw.io/plain. DO NOT EDIT.

package stmt

const ActivateJob = `
update _chrono
set
    active = true,
    last_heartbeat = $2
where name = $1
`

const CreateChronoTable = `
create table if not exists _chrono (
    name text primary key,
    active boolean not null,
    last_run timestamp not null,
    last_heartbeat timestamp not null
)
`

const HeartbeatJob = `
update _chrono
set
    last_heartbeat = $2
where name = $1
`

const InsertJob = `
insert into _chrono (
    name,
    active,
    last_run,
    last_heartbeat
)
values (
    $1,
    false,
    $2,
    '1970-01-01T00:00:00+00:00'::timestamptz
)
on conflict (name) do nothing
`

const SelectJob = `
select
    active, last_run, last_heartbeat
from _chrono
where name = $1
for update
`

const UpdateJob = `
update _chrono
set
    active = $2,
    last_run = $3,
    last_heartbeat = $4
where name = $1
`
